Parameters:
  BasicCalculatorFunction:
    Description: Basic calculator function Arn
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CommonFunctions/BasicCalculatorFunction

Resources:
  DivideByZero:
    Type: Custom::DivideByZero
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !Ref BasicCalculatorFunction
      Operands:
        - 0
        - 0
      Operator: "/"
