Parameters:
  BasicCalcFunction:
    Description: Basic calculator function Arn
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CommonFunctions/BasicCalcFunction

Resources:
  Add:
    Type: Custom::Add
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 2
        - 3
        - 5
      Operator: "+"

  Subtract:
    Type: Custom::Subtract
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 5
        - 3
        - 2
      Operator: "-"

  Multiply:
    Type: Custom::Multiply
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 2
        - 3
      Operator: "*"

  Divide:
    Type: Custom::Divide
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 6
        - 2
      Operator: "/"

  Modulus:
    Type: Custom::Modulus
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 6
        - 2
      Operator: "%"

  Log:
    Type: Custom::Log
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 8
        - 2
      Operator: log

  Pow:
    Type: Custom::Pow
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 2
        - 3
      Operator: pow

  Gcd:
    Type: Custom::Gcd
    Properties:
      ServiceToken: !Ref BasicCalcFunction
      Operands:
        - 2
        - 8
        - 16
      Operator: gcd

Outputs:
  Sum:
    Description: The sum of the operands in Add
    Value: !GetAtt Add.Value

  Difference:
    Description: The difference of the operands in Subtract
    Value: !GetAtt Subtract.Value

  Product:
    Description: The product of the operands in Multiply
    Value: !GetAtt Multiply.Value

  Quotient:
    Description: The quotient of the operands in Divide
    Value: !GetAtt Divide.Value

  Remainder:
    Description: The remainder of the operands in Modulus
    Value: !GetAtt Modulus.Value

  Log2:
    Description: The log base 2 of 8
    Value: !GetAtt Log.Value

  PowerOf2:
    Description: 2 to the power of 3
    Value: !GetAtt Pow.Value

  Gcd2:
    Description: The greatest common divisor of 2, 8 and 16
    Value: !GetAtt Gcd.Value
