AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambdas
  
Globals:
  Function:
    Timeout: 3

Resources:
  BasicCalcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: calc/
      Handler: app.lambda_handler
      Runtime: python3.7

Outputs:
  BasicCalcFunctionArn:
    Description: BasicCalc Lambda Function ARN
    Value: !GetAtt BasicCalcFunction.Arn
