AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Common Functions
  
Globals:
  Function:
    CodeUri: src/
    Runtime: python3.7
    Timeout: 3

Resources:
  BasicCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cf.basic_calculator.handler

  BasicCalculatorParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Basic Calculator Lambda Function ARN
      Type: String
      Name: !Sub /${AWS::StackName}/BasicCalculatorFunction
      Value: !GetAtt BasicCalculatorFunction.Arn

  NetworkCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cf.network_calculator.handler

  NetworkCalculatorParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Network Calculator Lambda Function ARN
      Type: String
      Name: !Sub /${AWS::StackName}/NetworkCalculatorFunction
      Value: !GetAtt NetworkCalculatorFunction.Arn

Outputs:
  BasicCalculatorFunctionArn:
    Description: Basic Calculator Lambda Function ARN
    Value: !GetAtt BasicCalculatorFunction.Arn

  BasicCalculatorFunctionParameter:
    Description: Basic Calculator Lambda Function Parameter
    Value: !Ref BasicCalculatorParameter

  NetworkCalculatorFunctionArn:
    Description: Network Calculator Lambda Function ARN
    Value: !GetAtt NetworkCalculatorFunction.Arn

  NetworkCalculatorFunctionParameter:
    Description: Network Calculator Lambda Function Parameter
    Value: !Ref NetworkCalculatorParameter
