AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Common Functions
  
Globals:
  Function:
    Timeout: 3

Resources:
  BasicCalcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: calc/
      Handler: app.lambda_handler
      Runtime: python3.7

  BasicCalcParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: BasicCalc Lambda Function ARN
      Type: String
      Name: !Sub /${AWS::StackName}/BasicCalcFunction
      Value: !GetAtt BasicCalcFunction.Arn

Outputs:
  BasicCalcFunctionArn:
    Description: BasicCalc Lambda Function ARN
    Value: !GetAtt BasicCalcFunction.Arn

  BasicCalcFunctionParameter:
    Description: BasicCalc Lambda Function Parameter
    Value: !Ref BasicCalcParameter
